name: Build Docker Image

on:
  push:
    branches:
      - master   # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Restore Docker Layer Cache
      - name: Restore Docker cache
        uses: actions/cache@v4.1.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # 5. Build Docker Image with Cache
      - name: Build Docker Image
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            --tag your-dockerhub-username/your-image-name:latest \
            .
